# Generated by Django 4.2.6 on 2023-11-01 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('fechadenacimiento', models.DateField(max_length=100)),
                ('documento', models.CharField(max_length=100)),
                ('domicilio', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('fechadenacimiento', models.DateField(max_length=100)),
                ('documento', models.CharField(max_length=100)),
                ('domicilio', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diasdelasemana', models.CharField(max_length=100)),
                ('fechadenacimiento', models.DateField(max_length=100)),
                ('alumno', models.ManyToManyField(blank=True, to='cursos.alumno')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.instructor')),
            ],
        ),
    ]
